# Generated by Django 3.2.9 on 2022-08-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywords',
            name='action_code',
            field=models.IntegerField(default=0),
        ),
    ]
