# Generated by Django 3.2.9 on 2022-08-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_logouseraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logouseraction',
            name='count',
        ),
        migrations.AddField(
            model_name='logouseraction',
            name='action_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='logouseraction',
            name='target_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
