# Generated by Django 3.2.9 on 2022-08-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_autolikesetting_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autolikesetting',
            name='start_time',
        ),
    ]
