# Generated by Django 3.2.9 on 2022-08-07 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_autofollowsetting_autoretweetsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoretweetsetting',
            name='user',
        ),
        migrations.AddField(
            model_name='autolikesetting',
            name='action_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='autolikesetting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AutoFollowSetting',
        ),
        migrations.DeleteModel(
            name='AutoRetweetSetting',
        ),
    ]
